### ISSUE TITLE
Let's talk about early commits

### ISSUE THREAD

**Issue by ionicc** [HAC-2020/FLIP#5]
I see that you guys learning and exploring Git by committing and making PRs. That's all good, But you can't make commits on the HAC repos before 2:00 PM 7th August.

Now we have two options:

1) Disqualification
2) We delete the commits and force push the with the initial commit. Then you can start committing after 2:00 PM.

Please don't close this issue and respond. Otherwise, we won't have a choice but to disqualify you.

**Comment by AthN3090** [comment]
We are sorry. we have already deleted the changes made by us.

**Comment by ionicc** [comment]
@AthN3090 Delete the commits as well. I'll tell you how:

```
git checkout master
git reset --hard HEAD~32
git push origin -f master
```

**Comment by ionicc** [comment]
I see that you've deleted the commits as well. Thank you so much. 

I'll close this issue now, Have a fun weekend yall!
